//Divisible By Five?
/*In the console, define a variable and set it equal to an integer value. Then write code that will console.log “TRUE” if the integer stored in your variable is divisible by 5, and “FALSE” otherwise.*/


//let x=33;
//Divisiblebyfive (x);

function Divisiblebyfive (x) { 
    if (x%5==0) {
    console.log ("true");}
    else {
      console.log ("false");
    }
   return;
  }
  
  // Less than 100?
  /*In the console, define two variables and set them each equal to an integer value. Then write code that will console.log “TRUE” if the sum of the numbers is less than 100, and “FALSE” otherwise.
  
  Try your code with the following pairs of values: (22,15), (83,34)*/
  
  let x=69;
  let y=20;
  
   Sum (x,y);
  
  function Sum (x,y) { 
    if ( x+y <=100) { 
      console.log ("true");}
  else{ 
    console.log ("false");
  }
  return;
  } 
  
  //Fibonacci
  /*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...*/
  
  let j=1;
  let y=1;
  let sum=0;
   function fib(x){
    for (i=1; i<=x ; i++){
    sum = j ;
    j=sum+y;
    y=sum ;
    console.log (sum);
    }
  }
  console.log (fib("10"))
  
  
  